GET http://localhost:3003/api/resumeEntrys/
###
POST http://localhost:3003/api/resumeEntrys/
content-type: application/json

{
    "username": "admin",
    "password": "password",
    "name": "rootUser"
}
###
DELETE http://localhost:3003/api/resumeEntrys/641f5cd7704e46a96363d755